---
- name: Start inbox--notion-publisher container
  become: true
  become_user: docker
  community.docker.docker_container:
    name: "{{ INBOX_NOTION_PUBLISHER_CONTAINER_NAME }}"
    image: javaster/notion-inbox-publisher:latest
    networks:
      - name: "{{ DOCKER_NETWORK_NAME }}"
    env:
      KAFKA_BROKERS: "{{ lookup('env', 'KAFKA_BROKERS') }}"
      NOTION_TOKEN: "{{ lookup('ansible.builtin.env', 'INBOX_NOTION_TOKEN') }}"
      NOTION_DB: "{{ lookup('ansible.builtin.env', 'INBOX_NOTION_DB') }}"
