---
- hosts: provision_kafka
  connection: local
  roles:
    - role: provision_ec2

- hosts: provision_kafka
  connection: local
  roles:
    - role: setup_ec2_dynamic_hosts

- hosts: dynamic_hosts
  become: true
  roles:
    - role: setup_ec2

- hosts: dynamic_hosts
  become: true
  roles:
    - role: test_ec2

- hosts: dynamic_hosts
  become: true
  roles:
    - role: setup_kafka