---
- hosts: provision_default_ec2
  connection: local
  vars:
    PROVISION_EC2_INSTANCE_NAME: inbox-bot-ec2-instance
    ansible_python_interpreter: "{{ lookup('ansible.builtin.env', 'Python_ROOT_DIR') }}/bin/python"
  roles:
    - role: provision_ec2
    - role: setup_ec2_dynamic_hosts

- hosts: dynamic_hosts
  become: true
  roles:
    - role: setup_inbox_bot_proxy_app
