  # Instance name
  PROVISION_EC2_INSTANCE_NAME: default-ec2-instance
  # Type of instance that will be provisioned
  PROVISION_EC2_INSTANCE_TYPE: t2.micro
  # Name of used security group
  PROVISION_EC2_SECURITY_GROUP_NAME: default-security-group
  # Name of image that will be used to launch the server
  PROVISION_EC2_IMAGE_ID: ami-0d1ddd83282187d18
  # Region where server will be provisioned
  PROVISION_EC2_REGION: eu-central-1
  # Name of key pair to connect to aws
  PROVISION_EC2_KEYPAIR: main-key-pair
  # Number of instances to launch
  PROVISION_EC2_NUMBER_OF_INSTANCES: 1
  SSH_PRIVATE_KEY_PATH: "{{ lookup('ansible.builtin.env', 'AWS_SSH_PRIVATE_KEY_PATH'), default='~/.ssh/id_rsa' }}"