---

- name: Create Security group
  amazon.aws.ec2_group:
    aws_access_key: "{{ lookup('ansible.builtin.env', 'AWS_EC2_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('ansible.builtin.env', 'AWS_EC2_SECRET_KEY') }}"
    name: "{{ security_group }}"
    description: 'Security Group with SSH rule'
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22 

- name: Launching EC2 instances
  community.aws.ec2_instance:
    aws_access_key: "{{ lookup('ansible.builtin.env', 'AWS_EC2_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('ansible.builtin.env', 'AWS_EC2_SECRET_KEY') }}"
    # profile: "{{ aws_boto_profile }}
    key_name: "{{ keypair }}"
    security_group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image }}" 
    state: present
    wait: yes
    wait_timeout: 300
    region: "{{ region }}"
    detailed_monitoring: no
    network:
      assign_public_ip: yes
    tags:
      Name: test-ec2