---
- name: Test docker installed properly
  hosts: aws
  remote_user: ubuntu
  become: true
  vars:
    ansible_python_interpreter: "/opt/hostedtoolcache/Python/3.9.16/x64/bin/python"

  tasks:
    - name: Start test container
      become: true
      become_user: docker
      community.docker.docker_container:
        name: test-hw
        image: hello-world
    
    - name: Stop test container
      become: true
      become_user: docker
      community.docker.docker_container:
        name: test-hw
        state: stopped
    
    - name: Remove test container
      become: true
      become_user: docker
      community.docker.docker_container:
        name: test-hw
        state: absent